error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT
display_errors = on
short_open_tag = off
post_max_size = 200M
upload_max_filesize = 200M
date.timezone = Europe/Moscow
memory_limit = 512M

error_log = /var/log/php/php.log
xdebug.log = /var/log/php/xdebug.log
